name: Profile README Generator

on:
  schedule:
    # Update every day at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile README

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate Snake Game
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: alira-xk
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --staged --quiet || git commit -m "Update GitHub stats"
          git push