name: Update README Stats

on:
  schedule:
    # Update stats every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Update GitHub Stats
      uses: anmol098/waka-readme-stats@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        SHOW_PROJECTS: "False"
        SHOW_PROFILE_VIEWS: "False"
        SHOW_DAYS_OF_WEEK: "False"
        SHOW_TIMEZONE: "False"
        SHOW_EDITORS: "False"
        SHOW_LANGUAGE_PER_REPO: "False"
        SHOW_LOC_CHART: "False"
        SHOW_LINES_OF_CODE: "True"
        SHOW_SHORT_INFO: "True"
        SHOW_COMMIT: "True"